version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/social-feed
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=social-feed
      - POSTGRES_PASSWORD=social-feed
      - POSTGRES_DB=social-feed_dev

# persist data beyond life of container
volumes:
  postgres_data:
