"""
Django settings for social_feed project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path

from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-9o3w)ifadj^jnjy^a2rbo6!@ra!mqw*^uwrc*7w2ia+g03=)82"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "account.apps.AccountConfig",  # use my authentication template before any others
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",  # record history
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.admindocs",
    # local apps other than accounting
    "images",
    "actions",
    # third party
    "crispy_forms",
    "social_django",
    "django_extensions",
    "easy_thumbnails",
]


CRISPY_TEMPLATE_PACK = 'bootstrap4'

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "social_feed.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",  # for messaging
            ],
        },
    },
]

WSGI_APPLICATION = "social_feed.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": str(BASE_DIR / "db.sqlite3")
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
#  go here if next is not provided
LOGIN_REDIRECT_URL = 'dashboard'
# all views using login decorator go here if not authenticated
LOGIN_URL = 'login'
LOGOUT_URL = 'logout'

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
MEDIA_URL = '/media/'  # serve media files uploaded from here
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')  # local path of residence


AUTHENTICATION_BACKENDS = [
    # if no user is returned using username and password, go to the email
    'django.contrib.auth.backends.ModelBackend',  # maintain default auth backend
    'account.authenticate.EmailAuthbackend',
    "social_core.backends.twitter.TwitterOAuth",
]

SOCIAL_AUTH_TWITTER_KEY = "ffptrcZ9Lwu6vEKKRPWTF9DBz"  # api KEY
SOCIAL_AUTH_TWITTER_SECRET = "314TNcpJdXIJrxZcY9QbZoFlXSRasmTmATE6xqUYy2WnuXmi7O"  # api SECRET
# BREARER TOKEN
# AAAAAAAAAAAAAAAAAAAAAFCnjAEAAAAAj8txDcpXaEq8w1lDGNkgu % 2B9TT5M % 3DG0THo1UxArwbqE9avSH5j4rsqF9eT8uf1KdBu4eKcN6Wpl6b7Z

# reverse url for specific app. alternate setup
ABSOLUTE_URL_OVERRIDES = {'auth.user': lambda u: reverse_lazy(
    'user_detail', args=[u.username])}

REDIS_HOST = 'localhost'
REDIS_PORT = 6379
REDIS_DB = 0
